In [21]:
#numpy 
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(type(arr))
print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
<class 'numpy.ndarray'>
int32


In [ ]:
import mat